server: 
  port: 9001
  
spring: 
  application: 
    name: feign-consumer


feign: 
  hystrix: 
    enabled: true

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1112/eureka/
