---
server: 
  port: 8090
  
spring: 
  profiles: clientone
  application: 
    name: hello-service

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/

---
server: 
  port: 8091
  
spring: 
  profiles: clienttwo
  application: 
    name: hello-service

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/    