server: 
  port: 7001
spring: 
  application: 
    name: config-server
  cloud: 
    config: 
      username: ddwangw
      password: ddwanglife@wxay#5fk
      label: master
      server: 
        git: 
          uri: https://github.com/ddwangw/springcloud-learning
          searchPaths: /config-repo/**

          
