server: 
  port: 7001
  
spring: 
  application:
     name: config-server
  cloud: 
    config: 
       username: ddwangw
       password: ddwanglife@wxay#5fk
       server: 
        git: 
          uri: https://github.com/ddwangw/springcloud-learning.git
          searchPaths: config-repo
